// @ts-check
/**
 * ESLint flat config.
 *
 * Layered so each file type gets what it needs and nothing it doesn't:
 *   1. TypeScript everywhere, with type-aware rules (this codebase is financial
 *      arithmetic — an unawaited promise or an unchecked `any` is a wrong number,
 *      not a style issue)
 *   2. React + hooks + a11y for .tsx only
 *   3. Relaxations for tests and scripts
 *
 * Pinned to ESLint 9: eslint-plugin-react and eslint-plugin-jsx-a11y do not yet
 * declare support for ESLint 10.
 */
import js from '@eslint/js'
import vitest from '@vitest/eslint-plugin'
import prettier from 'eslint-config-prettier'
import importX from 'eslint-plugin-import-x'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      '.output/**',
      '.vinxi/**',
      '.tanstack/**',
      'src/routeTree.gen.ts', // generated by TanStack Router
      'coverage/**',
    ],
  },

  // ── Base: every TS/JS file ────────────────────────────────────────────────
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.node, ...globals.browser },
    },
    plugins: { 'import-x': importX },
    settings: {
      // import-x ships its own resolver, so no extra resolver package is needed.
      // TypeScript already verifies that every import resolves; this exists only
      // so the cycle and ordering rules can follow the graph.
      'import-x/resolver-next': [importX.createNodeResolver()],
    },
    rules: {
      // ---- Correctness ----------------------------------------------------
      // A dropped promise in an import or price fetch fails silently and leaves
      // partial data behind; both of these have caught real bugs in this domain.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-unnecessary-condition': 'warn',
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],

      // Rakuten pads every Japanese text field with U+3000 (full-width space),
      // so the parsers must match it literally in strings and regexes. Only
      // stray whitespace in actual code is a mistake.
      'no-irregular-whitespace': [
        'error',
        { skipStrings: true, skipRegExps: true, skipTemplates: true, skipComments: true },
      ],

      // ---- Money safety ---------------------------------------------------
      // Decimal.js instances must never be coerced into template strings or
      // arithmetic — `${someDecimal}` silently produces a float-formatted value.
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        { allowNumber: true, allowBoolean: false, allowNullish: false },
      ],
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-unsafe-argument': 'error',

      // ---- Style / clarity ------------------------------------------------
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'off', // used deliberately with noUncheckedIndexedAccess

      // ---- Imports --------------------------------------------------------
      'import-x/no-duplicates': 'error',
      'import-x/no-cycle': ['error', { maxDepth: 6 }],
      'import-x/order': [
        'warn',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          'newlines-between': 'never',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
    },
  },

  // ── React + accessibility: .tsx only ──────────────────────────────────────
  {
    files: ['**/*.tsx'],
    plugins: {
      react,
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    languageOptions: {
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: globals.browser,
    },
    settings: { react: { version: 'detect' } },
    rules: {
      ...react.configs.flat.recommended.rules,
      ...react.configs.flat['jsx-runtime'].rules, // React 19 — no React import needed
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,

      // ---- Accessibility, tightened ---------------------------------------
      // Radix primitives are unstyled and unlabelled by default, so these are
      // the rules most likely to catch a genuine problem here.
      'jsx-a11y/anchor-is-valid': 'error',
      'jsx-a11y/alt-text': 'error',
      'jsx-a11y/aria-props': 'error',
      'jsx-a11y/aria-role': 'error',
      'jsx-a11y/click-events-have-key-events': 'error',
      'jsx-a11y/no-static-element-interactions': 'error',
      'jsx-a11y/label-has-associated-control': [
        'error',
        { assert: 'either', depth: 3 },
      ],
      'jsx-a11y/no-autofocus': ['warn', { ignoreNonDOM: true }],
      // Charts and the calendar grid carry data — they need accessible names.
      'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
      'jsx-a11y/interactive-supports-focus': 'error',

      // ---- React ----------------------------------------------------------
      'react/prop-types': 'off', // TypeScript covers this
      'react/jsx-no-target-blank': 'error',
      'react/jsx-key': ['error', { checkFragmentShorthand: true }],
      'react/no-array-index-key': 'warn',
      'react/self-closing-comp': 'warn',
      'react/jsx-boolean-value': ['warn', 'never'],
    },
  },

  // ── Tests ────────────────────────────────────────────────────────────────
  {
    files: ['**/*.test.ts', '**/*.test.tsx'],
    plugins: { vitest },
    rules: {
      ...vitest.configs.recommended.rules,
      // Fixtures deliberately build partial objects and cast them.
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      'vitest/expect-expect': 'error',
      'vitest/no-identical-title': 'error',
      'vitest/valid-expect': 'error',
    },
  },

  // ── Routes ───────────────────────────────────────────────────────────────
  {
    files: ['src/routes/**/*.tsx', 'src/routes/**/*.ts'],
    rules: {
      // `throw redirect({...})` is TanStack Router's documented way to divert
      // navigation from a loader or guard. The thrown value is a router signal,
      // deliberately not an Error, so this rule does not apply here.
      '@typescript-eslint/only-throw-error': 'off',
    },
  },

  // ── Diagnostic scripts ───────────────────────────────────────────────────
  {
    files: ['src/scripts/**/*.ts'],
    rules: {
      'no-console': 'off', // console output is the entire point
    },
  },

  // This config file itself is plain JS outside the tsconfig project, so
  // type-aware rules cannot run on it.
  {
    files: ['eslint.config.js', '*.config.js'],
    extends: [tseslint.configs.disableTypeChecked],
  },

  // Must stay last: disables anything that would fight a formatter.
  prettier,
)
