/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedImportRouteImport } from './routes/_authed/import'
import { Route as AuthedNisaRouteImport } from './routes/_authed/nisa'
import { Route as AuthedPositionsRouteImport } from './routes/_authed/positions'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedStatsRouteImport } from './routes/_authed/stats'
import { Route as AuthedTaxRouteImport } from './routes/_authed/tax'
import { Route as AuthedTradesRouteImport } from './routes/_authed/trades'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedImportRoute = AuthedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNisaRoute = AuthedNisaRouteImport.update({
  id: '/nisa',
  path: '/nisa',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPositionsRoute = AuthedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStatsRoute = AuthedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTaxRoute = AuthedTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTradesRoute = AuthedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/calendar': typeof AuthedCalendarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/import': typeof AuthedImportRoute
  '/nisa': typeof AuthedNisaRoute
  '/positions': typeof AuthedPositionsRoute
  '/settings': typeof AuthedSettingsRoute
  '/stats': typeof AuthedStatsRoute
  '/tax': typeof AuthedTaxRoute
  '/trades': typeof AuthedTradesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/calendar': typeof AuthedCalendarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/import': typeof AuthedImportRoute
  '/nisa': typeof AuthedNisaRoute
  '/positions': typeof AuthedPositionsRoute
  '/settings': typeof AuthedSettingsRoute
  '/stats': typeof AuthedStatsRoute
  '/tax': typeof AuthedTaxRoute
  '/trades': typeof AuthedTradesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/signin': typeof SigninRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/import': typeof AuthedImportRoute
  '/_authed/nisa': typeof AuthedNisaRoute
  '/_authed/positions': typeof AuthedPositionsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/stats': typeof AuthedStatsRoute
  '/_authed/tax': typeof AuthedTaxRoute
  '/_authed/trades': typeof AuthedTradesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/calendar'
    | '/dashboard'
    | '/import'
    | '/nisa'
    | '/positions'
    | '/settings'
    | '/stats'
    | '/tax'
    | '/trades'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/calendar'
    | '/dashboard'
    | '/import'
    | '/nisa'
    | '/positions'
    | '/settings'
    | '/stats'
    | '/tax'
    | '/trades'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/signin'
    | '/_authed/calendar'
    | '/_authed/dashboard'
    | '/_authed/import'
    | '/_authed/nisa'
    | '/_authed/positions'
    | '/_authed/settings'
    | '/_authed/stats'
    | '/_authed/tax'
    | '/_authed/trades'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SigninRoute: typeof SigninRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/import': {
      id: '/_authed/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthedImportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nisa': {
      id: '/_authed/nisa'
      path: '/nisa'
      fullPath: '/nisa'
      preLoaderRoute: typeof AuthedNisaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/positions': {
      id: '/_authed/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthedPositionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stats': {
      id: '/_authed/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthedStatsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tax': {
      id: '/_authed/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof AuthedTaxRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trades': {
      id: '/_authed/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthedTradesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedImportRoute: typeof AuthedImportRoute
  AuthedNisaRoute: typeof AuthedNisaRoute
  AuthedPositionsRoute: typeof AuthedPositionsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedStatsRoute: typeof AuthedStatsRoute
  AuthedTaxRoute: typeof AuthedTaxRoute
  AuthedTradesRoute: typeof AuthedTradesRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedImportRoute: AuthedImportRoute,
  AuthedNisaRoute: AuthedNisaRoute,
  AuthedPositionsRoute: AuthedPositionsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedStatsRoute: AuthedStatsRoute,
  AuthedTaxRoute: AuthedTaxRoute,
  AuthedTradesRoute: AuthedTradesRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
